ALTER TABLE Books
ADD CONSTRAINT authorID
FOREIGN KEY (authorID) REFERENCES Authors(authorID);

ALTER TABLE Orders
ADD CONSTRAINT bookID
FOREIGN KEY (bookID) REFERENCES Books(bookID);

ALTER TABLE Reviews
ADD CONSTRAINT reviewerID
FOREIGN KEY (reviewerID) REFERENCES Members(memberID);
